spring:
  application:
    name: EurekaServer

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-url: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8765
